packages:
  - "apps/*"
  - "packages/*"
catalog:
  typescript: ^5.7.2
  esbuild : ^0.24.2
  jsonwebtoken: ^9.0.2
  "@types/jsonwebtoken": ^9.0.7
dependencies:
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^13.0.0